### ISSUE TITLE
Format Salah

### ISSUE THREAD

**Issue by taaehk** [ariffyasri/ProSolve#10]
.ans?
.clas?

contoh nya:
Artificial Intelligence sepatutnya begitu, contoh:
https://github.com/AlexanderEric/IRIS
cuba download, unzip, start yang didownload itu dari res;dir aku

**Comment by ariffyasri** [comment]
Can you give the link to the folder that contains this question? I don't understand the question, which format is wrong?

**Comment by AlexanderEric** [comment]
.cls is not readable for sapi(a.i)
So does .ans

**Comment by ariffyasri** [comment]
Not related to the repo. Reopen this issue if you think it's related.
